# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(721, 409)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 811, 581))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.0625 rgba(5, 24, 30, 255), stop:0.142045 rgba(2, 23, 44, 255), stop:0.272727 rgba(2, 24, 48, 255), stop:0.4375 rgba(3, 23, 42, 255), stop:0.545455 rgba(4, 25, 30, 255), stop:0.670455 rgba(4, 25, 30, 255));}")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(420, -380, 331, 1171))
        self.widget_2.setStyleSheet("image: url(:/newpic/d3eaaee187dd5812a689cb989b25c2b8.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 10, 421, 161))
        self.label.setStyleSheet("font: 36pt \"Post No Bills Colombo\";\n"
"color: qconicalgradient(cx:0.517, cy:0.511773, angle:39.9, stop:0.698864 rgba(22, 75, 155, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font:Bold;\n"
"")
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(50, 70, 41, 281))
        self.widget_3.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0.170455 rgba(2, 24, 46, 255), stop:0.238636 rgba(3, 23, 45, 255), stop:0.431818 rgba(3, 23, 43, 255), stop:0.505682 rgba(5, 42, 77, 255), stop:0.511364 rgba(2, 24, 46, 255), stop:0.55 rgba(6, 40, 59, 255), stop:0.698864 rgba(3, 24, 28, 255), stop:0.897727 rgba(2, 30, 46, 255));")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 301, 50))
        self.label_2.setStyleSheet("\n"
"FONT:bOLD;\n"
"font: 20pt \"Nirmala UI\";\n"
"\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0.170455 rgba(255, 255, 255, 255), stop:0.227273 rgba(255, 255, 255, 255), stop:0.375 rgba(255, 255, 255, 255), stop:0.397727 rgba(22, 158, 191, 255), stop:0.477273 rgba(255, 255, 255, 255), stop:0.545455 rgba(255, 255, 255, 255), stop:0.556818 rgba(162, 222, 236, 255), stop:0.897727 rgba(255, 255, 255, 255));")
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setEnabled(True)
        self.widget_4.setGeometry(QtCore.QRect(-10, 380, 141, 41))
        self.widget_4.setStyleSheet("image: url(:/newpic/logo_white.png);\n"
"height:59px;\n"
"width:20px;")
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(100, 310, 150, 41))
        self.label_4.setStyleSheet("color:white;\n"
"text-align:justify;")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(95, 160, 311, 81))
        self.plainTextEdit.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"text-align:justify;\n"
"font-size:8px;\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "BURQ SUITE"))
        self.label_2.setText(_translate("Dialog", "ALL IN ONE RISC-V SUITE"))
        self.label_4.setText(_translate("Dialog", "Loading Configuration ..."))
        self.plainTextEdit.setPlainText(_translate("Dialog", "System on Chip Configuration, Customization, Designinig, Development Suite. Core Customization, Configuration, Development, Designing Suite. Verification Engineering, Self Checking Tests. Software Development Kit (SDK) based on using C Tests."))
import newpic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
